### ISSUE TITLE
Build resolves incorrect version of ruduino when cargo.lock cleaned

### ISSUE THREAD

**Issue by schil227** [avr-rust/blink#28]
The cargo.toml file references `ruduino = "0.2"`, however if the cargo.lock file is removed (explicitly targeting 0.2.0) this will pull the latest (currently 0.2.7), which breaks the build. It could be fixed by changing the toml to specifically target 0.2.0, but it'll probably be more useful to update the code to use the newest version.

**Comment by dylanmckay** [comment]
I've updated the code to `ruduino 0.3`, so this should be fixed. Thanks for raising this.
