### ISSUE TITLE
blinking to fast

### ISSUE THREAD

**Issue by vingeni** [avr-rust/blink#34]
Hi, the led is blinking too fast.
This is probably due to this [bug on avr-delay](https://github.com/avr-rust/delay/issues/11) ?

It worked well with the previous "hacky loop"

**Comment by crazcalm** [comment]
@vingeni I am not sure if you are still using Rust to mess with your Arduino, but there is a [avr-hal](https://github.com/Rahix/avr-hal) crate. Their blinking example works for me.

**Comment by darionesi** [comment]
I've added 

```toml
[profiles.release]
lto = true
```

as per [this suggestion](https://www.reddit.com/r/rust/comments/mjkp9v/comment/gx7hrbh/) I've found on reddit and now the code in this repo makes the arduino blink as expected

**Comment by bmgxyz** [comment]
That suggestion worked for me, although it looks like the correct key is `profile` (singular), not `profiles` (plural).

I used:

```toml
[profile.release]
lto = true
```

See [this section](https://doc.rust-lang.org/cargo/reference/profiles.html) in The Cargo Book.
