### ISSUE TITLE
Does it work with dependencies?

### ISSUE THREAD

**Issue by TheNotary** [avr-rust/blink#35]
For instance, I'm currently working with a project in Arduino's C, and it uses `adafruit/RTClib`.  How exactly do we perform something like the following in rust instead of C?  

```
#include "RTClib.h"
#define DHTPIN 2
#define DHTTYPE DHT11

DHT dht(DHTPIN, DHTTYPE);
dht.begin();
float h = dht.readHumidity();
Serial.print(h);
```

**Comment by stappersg** [comment]
This valid question does not below here.  In [How to ask smart questions](http://www.catb.org/~esr/faqs/smart-questions.html) is documented how to proceed.

@TheNotary and all others, do know that is OK to post here a link to answer of _How read DHT sensor in Rust?_
